export type { IsoDateString, IsoDateTimeString, PagedResult } from "./common";
export type {
  ApiMessageBody,
  AuthLoginBody,
  AuthRegistroBody,
  AuthSessionResponse,
  HospedeCreateBody,
  HospedeUpdateBody,
  PousadaCreateBody,
  PousadaUpdateBody,
  QuartoCreateBody,
  QuartoUpdateBody,
  ReservaCreateBody,
  ReservaUpdateBody,
  VerificarDisponibilidadeBody,
  CalendarioExternoCreateBody,
  CalendarioExternoUpdateBody,
} from "./dto";
export type {
  BloqueioAgenda,
  CalendarioCanal,
  CalendarioExterno,
  CalendarioSyncResult,
  Hospede,
  IntegracaoICal,
  Metricas,
  OcupacaoPeriodo,
  Pousada,
  Quarto,
  Reserva,
  ReservaOrigem,
  Usuario,
  VerificarDisponibilidadeResponse,
} from "./entities";

